name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf autotools-dev libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer kivy

      - name: Build Android APK
        run: |
          # هذه الأوامر تقوم بالبناء يدوياً لتجنب قيود الأمان
          yes | buildozer android debug
        
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
          
