name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build with Buildozer
        uses: kivy/buildozer-action@dd697e84992110c95356e92c43105df54992f447 # v1.5.0
        with:
          command: buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea23f8b31550291497d519b59 # v4.4.3
        with:
          name: my-app-apk
          path: bin/*.apk
          

